apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_HOST: "postgres-service"
  RABBITMQ_HOST: "rabbitmq-service"
  USER_QUEUE_NAME: "users-queue"
  PAYMENT_QUEUE_NAME: "payments-queue"