services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - apps_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apps_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalog_user -d catalog_db"]
      interval: 5s     
      timeout: 5s
      retries: 5
      start_period: 10s

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SenhaAdmin123!
      MYSQL_DATABASE: users_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - apps_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSenhaAdmin123!"]
      interval: 5s
      timeout: 5s
      retries: 10

  catalog-api:
    image: splinterxsr/catalogapi:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
      POSTGRES_HOST: postgres
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - apps_network

  users-api:
    image: anafmel/usersapi:latest
    restart: always
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MYSQL_USER: root              
      MYSQL_ROOT_PASSWORD: SenhaAdmin123! 
      MYSQL_DATABASE: users_db
      MYSQL_HOST: mysql
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      JWT_ISSUER: FiapCloudGames
      JWT_SECONDS: 3600
      JWT_KEY: M72gsn/ZtfvDSgyBgWNBOYf8HAHBO7FGIwiKPtwipmdMY6ZbdgrJ66yBLnXKk9O8P6fjj7G+BoE5+Ou/xfEgNQ==
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - apps_network

  catalog-worker:
    image: splinterxsr/catalogworker:latest
    restart: always
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
      POSTGRES_HOST: postgres
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
      PAYMENT_QUEUE_NAME: payments-queue
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - apps_network

  notifications-worker:
    image: splinterxsr/notificationsworker:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
      USER_QUEUE_NAME: users-queue
      PAYMENT_QUEUE_NAME: payments-queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - apps_network

  payments-worker:
    image: anafmel/paymentsworker:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
      ORDER_PLACED_QUEUE_NAME: orders-placed-queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - apps_network 

volumes:
  rabbitmq_data:
  postgres_data:
  mysql_data:

networks:
  apps_network:
    driver: bridge