apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
  labels:
    app: payments-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
    spec:
      containers:
        - name: payments-worker
          image: anafmel/paymentsworker:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST
            - name: ORDER_PLACED_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDER_PLACED_QUEUE_NAME
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"