apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: anafmel/usersapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:       
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_PASS
            
            - name: MARIADB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MARIADB_HOST
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MARIADB_DATABASE
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MARIADB_USER
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MARIADB_ROOT_PASSWORD
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_ISSUER
            - name: JWT_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_SECONDS
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_KEY

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"  
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3         

---

apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  labels:
    app: users-api
spec:
  type: NodePort
  selector:
    app: users-api
  ports:
    - port: 80         
      targetPort: 8080  
      nodePort: 30100   
      protocol: TCP
      name: http