apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  namespace: default
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
      - name: user-service
        url: http://users-api:8080
        routes:
          - name: user-auth-route
            paths:
              - /user/auth
            strip_path: false
          - name: user-protected-route
            paths:
              - /user
            strip_path: false
            plugins:
              - name: jwt
                config:
                  claims_to_verify:
                    - exp
                  key_claim_name: iss

      - name: catalog-service
        url: http://catalog-api:8080
        routes:
          - name: catalog-protected-route
            paths:
              - /catalog
              - /game
            strip_path: false
            plugins:
              - name: jwt
                config:
                  claims_to_verify:
                    - exp
                  key_claim_name: iss

    consumers:
      - username: fiap-cloud-games-consumer
        jwt_secrets:
          - key: FiapCloudGames
            secret: M72gsn/ZtfvDSgyBgWNBOYf8HAHBO7FGIwiKPtwipmdMY6ZbdgrJ66yBLnXKk9O8P6fjj7G+BoE5+Ou/xfEgNQ==
            algorithm: HS512