apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "sqs,lambda,iam,sns"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  type: ClusterIP
  selector:
    app: localstack
  ports:
    - port: 4566
      targetPort: 4566
      name: edge