global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'users-api'
    static_configs:
      - targets: ['users-api:8080']

  - job_name: 'catalog-api'
    static_configs:
      - targets: ['catalog-api:8080']