apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: catalog_user
  POSTGRES_PASSWORD: catalog_pass
  POSTGRES_DB: catalog_db
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  MYSQL_USER: root             
  MYSQL_ROOT_PASSWORD: SenhaAdmin123! 
  MYSQL_DATABASE: users_db
  JWT_KEY: M72gsn/ZtfvDSgyBgWNBOYf8HAHBO7FGIwiKPtwipmdMY6ZbdgrJ66yBLnXKk9O8P6fjj7G+BoE5+Ou/xfEgNQ==